### ISSUE TITLE
papercut: add optional prefix input to DA

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-account-infrastructure-base#105]
### Description

- optional input parameter
- If prefix input is set to a non empty string, then append the prefix to all created resource name.

### New or affected modules

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
https://github.com/terraform-ibm-modules/terraform-ibm-account-infrastructure-base/pull/110
