### ISSUE TITLE
Expose all parameters from base module in the DA

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-account-infrastructure-base#129]
Variables at https://github.com/terraform-ibm-modules/terraform-ibm-account-infrastructure-base/blob/main/variables.tf should be exposed as the "DA" level - https://github.com/terraform-ibm-modules/terraform-ibm-account-infrastructure-base/tree/main/solutions/account-infrastructure-base

**Comment by rajatagarwal-ibm** [comment]
PR merged - https://github.com/terraform-ibm-modules/terraform-ibm-account-infrastructure-base/pull/130
