### ISSUE TITLE
Remove support for ATracker route + cos set up

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-account-infrastructure-base#70]
Observability DA will handle this - but lets hold off until that is ready

**Comment by vburckhardt** [comment]
Hi @MatthewLemmond - there is an issue in https://github.com/terraform-ibm-modules/terraform-ibm-account-infrastructure-base/issues/27 . kms and cos related variable should be set to null by default under https://github.com/terraform-ibm-modules/terraform-ibm-account-infrastructure-base/blob/f646074f7ff8c0b8761c8bc981c75a784b1bfde1/solutions/account-infrastructure-base/variables.tf#L28 (like in the root module)

**Comment by MatthewLemmond** [comment]
created https://github.com/terraform-ibm-modules/terraform-ibm-account-infrastructure-base/pull/91 to fix that, was not caught by tests due to all of our tests provisioning atracker and COS

**Comment by ocofaigh** [comment]
Added in https://github.com/terraform-ibm-modules/terraform-ibm-account-infrastructure-base/pull/87
